-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\lab2\CALC_MAG_AND_PHASE_FIX_POIN_pkg.vhd
-- Created: 2023-01-11 03:13:15
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE CALC_MAG_AND_PHASE_FIX_POIN_pkg IS
  TYPE vector_of_unsigned33 IS ARRAY (NATURAL RANGE <>) OF unsigned(32 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
END CALC_MAG_AND_PHASE_FIX_POIN_pkg;

